openapi: "3.0.0"
info:
  title: Perch Mount API
  version: "1.0"
servers:
  - url: https://api.server.test/v1

paths:
  /members:
    get:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberPositionIDsQuery"
      responses:
        "200":
          $ref: "#/components/responses/MembersResponse"
    post:
      tags:
        - Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostMemberRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MemberResponse"

  /members/{MemberID}:
    get:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/MemberResponse"
    patch:
      tags:
        - Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchMemberRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MemberResponse"

  /projects:
    get:
      tags:
        - Project
      responses:
        "200":
          $ref: "#/components/responses/ProjectsResponse"
    post:
      tags:
        - Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostProjectRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/ProjectResponse"

  /perch_mounts:
    get:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/ProjectIDsQuery"
        - $ref: "#/components/parameters/ClaimByIDsQuery"
        - $ref: "#/components/parameters/HabitatIDsQuery"
        - $ref: "#/components/parameters/PerchMountTerminatedQuery"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountsResponse"

    post:
      tags:
        - Perch Mount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPerchMountRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}:
    get:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    patch:
      tags:
        - Perch Mount
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}/claimer:
    put:
      tags:
        - Perch Mount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutPerchMountClaimerRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    delete:
      tags:
        - Perch Mount
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}/termination:
    put:
      tags:
        - Perch Mount
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    delete:
      tags:
        - Perch Mount
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}/priority:
    put:
      tags:
        - Perch Mount
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    delete:
      tags:
        - Perch Mount
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /sections:
    get:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/PerchMountIDsQuery"
        - $ref: "#/components/parameters/SectionSwappedDateFromQuery"
        - $ref: "#/components/parameters/SectionSwappedDateToQuery"
        - $ref: "#/components/parameters/SectionSwapperIDsQuery"
      responses:
        "200":
          $ref: "#/components/responses/SectionsResponse"
    post:
      tags:
        - Section
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostSectionRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/SectionResponse"

  /sections/{SectionID}:
    get:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/SectionIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/SectionResponse"

    patch:
      tags:
        - Section
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchSectionRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/SectionResponse"

  /media:
    get:
      tags:
        - Media
      parameters:
        - $ref: "#/components/parameters/ProjectIDsQuery"
        - $ref: "#/components/parameters/PerchMountIDsQuery"
        - $ref: "#/components/parameters/SectionIDsQuery"
        - $ref: "#/components/parameters/MediaStatusQuery"
        - $ref: "#/components/parameters/IndividualsIsTaggedQuery"
        - $ref: "#/components/parameters/IndividualsRingNumberSearchQuery"
        - $ref: "#/components/parameters/IndividualsPreyIdentifiedStatusQuery"
        - $ref: "#/components/parameters/IndividualsHasPreyQuery"
        - $ref: "#/components/parameters/IndividualsPreyInaturalistTaxaIDSearchQuery"
        - $ref: "#/components/parameters/TaxonOrderByHumanQuery"
        - $ref: "#/components/parameters/TaxonOrderByAIQuery"
        - $ref: "#/components/parameters/OffsetQuery"
        - $ref: "#/components/parameters/LimitQuery"

      responses:
        "200":
          $ref: "#/components/responses/MediaResponse"

  /media/{MediumID}:
    get:
      tags:
        - Media
      parameters:
        - $ref: "#/components/parameters/MediumIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/MediumResponse"

  /unreviewed_media/detected:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUnreviewedMediaByDetectedRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /unreviewed_media/empty_checked:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUnreviewedMediaByEmptyCheckedRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /reviewed_media:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostReviewMediaRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /accidental_media:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostAccidentalMediaRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /new_data:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostNewDataRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/PostNewDataResponse"

  /individuals/{IndividualID}:
    get:
      tags:
        - Individuals
      parameters:
        - $ref: "#/components/parameters/IndividualIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/IndividualResponse"

    patch:
      tags:
        - Individuals
      parameters:
        - $ref: "#/components/parameters/IndividualIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/IndividualResponse"

  /individuals/preys:
    post:
      tags:
        - Individuals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostIdentifiedPreyIndividualsRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/IndividualResponse"

  /behaviors:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/BehaviorsResponse"

    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/BehaviorResponse"

  /positions:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/PositionsResponse"

  /habitats:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/PositionsResponse"

  /cameras:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/CamerasResponse"
    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/CameraResponse"

  /events:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/EventsResponse"
    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/EventResponse"

  /mount_types:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/MountTypeResponse"
    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/MountTypesResponse"

  /mount_layers:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/MountLayersResponse"

  /species:
    get:
      tags:
        - species
      parameters:
        - $ref: "#/components/parameters/SpeciesChineseNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesEndemismQuery"
        - $ref: "#/components/parameters/SpeciesEnglishNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesFamilyQuery"
        - $ref: "#/components/parameters/SpeciesNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesOrderQuery"
        - $ref: "#/components/parameters/SpeciesScientificNameSearchQuery"
      responses:
        "200":
          $ref: "#/components/responses/SpeciesListResponse"

  /species/{TaxonOrder}:
    get:
      tags:
        - species
      parameters:
        - $ref: "#/components/parameters/SpeciesTaxonOrderPathParam"
      responses:
        "200":
          $ref: "#/components/responses/SpeciesResponse"

components:
  responses:
    $ref: "./responses.yml"

  parameters:
    $ref: "./parameters.yml"

  schemas:
    $ref: "./schemas.yml"
