openapi: "3.0.0"
info:
  title: Perch Mount API
  version: "1.0"
servers:
  - url: https://api.server.test/v1

paths:
  /ping:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong

  /members:
    get:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberPositionIDsQuery"
      responses:
        "200":
          $ref: "#/components/responses/MembersResponse"
    post:
      tags:
        - Member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostMemberRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MemberResponse"

  /members/{MemberID}:
    get:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/MemberResponse"
    patch:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberIDPathParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchMemberRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MemberResponse"

  /projects:
    get:
      tags:
        - Project
      responses:
        "200":
          $ref: "#/components/responses/ProjectsResponse"
    post:
      tags:
        - Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostProjectRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/ProjectResponse"

  /perch_mounts:
    get:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/ProjectIDsQuery"
        - $ref: "#/components/parameters/ClaimByIDsQuery"
        - $ref: "#/components/parameters/HabitatIDsQuery"
        - $ref: "#/components/parameters/PerchMountTerminatedQuery"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountsResponse"

    post:
      tags:
        - Perch Mount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPerchMountRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}:
    get:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    patch:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}/claimer:
    put:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutPerchMountClaimerRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    delete:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}/termination:
    put:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    delete:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /perch_mounts/{PerchMountID}/priority:
    put:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"
    delete:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/PerchMountResponse"

  /sections:
    get:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/PerchMountIDsQuery"
        - $ref: "#/components/parameters/SectionSwappedDateFromQuery"
        - $ref: "#/components/parameters/SectionSwappedDateToQuery"
        - $ref: "#/components/parameters/SectionSwapperIDsQuery"
      responses:
        "200":
          $ref: "#/components/responses/SectionsResponse"
    post:
      tags:
        - Section
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostSectionRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/SectionResponse"

  /sections/{SectionID}:
    get:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/SectionIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/SectionResponse"

    patch:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/SectionIDPathParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchSectionRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/SectionResponse"

  /media:
    get:
      tags:
        - Media
      parameters:
        - $ref: "#/components/parameters/ProjectIDsQuery"
        - $ref: "#/components/parameters/PerchMountIDsQuery"
        - $ref: "#/components/parameters/SectionIDsQuery"
        - $ref: "#/components/parameters/MediaStatusQuery"
        - $ref: "#/components/parameters/IndividualsIsTaggedQuery"
        - $ref: "#/components/parameters/IndividualsRingNumberSearchQuery"
        - $ref: "#/components/parameters/IndividualsPreyIdentifiedStatusQuery"
        - $ref: "#/components/parameters/IndividualsHasPreyQuery"
        - $ref: "#/components/parameters/IndividualsPreyInaturalistTaxaIDSearchQuery"
        - $ref: "#/components/parameters/TaxonOrderByHumanQuery"
        - $ref: "#/components/parameters/TaxonOrderByAIQuery"
        - $ref: "#/components/parameters/OffsetQuery"
        - $ref: "#/components/parameters/LimitQuery"

      responses:
        "200":
          $ref: "#/components/responses/MediaResponse"

  /media/{MediumID}:
    get:
      tags:
        - Media
      parameters:
        - $ref: "#/components/parameters/MediumIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/MediumResponse"

  /unreviewed_media/detected:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUnreviewedMediaByDetectedRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /unreviewed_media/empty_checked:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUnreviewedMediaByEmptyCheckedRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /reviewed_media:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostReviewMediaRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /accidental_media:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostAccidentalMediaRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/MeidumPostResponse"

  /new_data:
    post:
      tags:
        - Media
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostNewDataRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/PostNewDataResponse"

  /individuals/{IndividualID}:
    get:
      tags:
        - Individuals
      parameters:
        - $ref: "#/components/parameters/IndividualIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/IndividualResponse"

    patch:
      tags:
        - Individuals
      parameters:
        - $ref: "#/components/parameters/IndividualIDPathParam"
      responses:
        "200":
          $ref: "#/components/responses/IndividualResponse"

  /individuals/preys:
    post:
      tags:
        - Individuals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostIdentifiedPreyIndividualsRequestBody"
      responses:
        "200":
          $ref: "#/components/responses/IndividualResponse"

  /behaviors:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/BehaviorsResponse"

    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/BehaviorResponse"

  /positions:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/PositionsResponse"

  /habitats:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/PositionsResponse"

  /cameras:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/CamerasResponse"
    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/CameraResponse"

  /events:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/EventsResponse"
    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/EventResponse"

  /mount_types:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/MountTypeResponse"
    post:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/MountTypesResponse"

  /mount_layers:
    get:
      tags:
        - Options
      responses:
        "200":
          $ref: "#/components/responses/MountLayersResponse"

  /species:
    get:
      tags:
        - species
      parameters:
        - $ref: "#/components/parameters/SpeciesChineseNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesEndemismQuery"
        - $ref: "#/components/parameters/SpeciesEnglishNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesFamilyQuery"
        - $ref: "#/components/parameters/SpeciesNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesOrderQuery"
        - $ref: "#/components/parameters/SpeciesScientificNameSearchQuery"
      responses:
        "200":
          $ref: "#/components/responses/SpeciesListResponse"

  /species/{TaxonOrder}:
    get:
      tags:
        - species
      parameters:
        - $ref: "#/components/parameters/SpeciesTaxonOrderPathParam"
      responses:
        "200":
          $ref: "#/components/responses/SpeciesResponse"

components:
  schemas:
    PostMemberRequestBody:
      $ref: "./schemas.yml#/PostMemberRequestBody"
    PatchMemberRequestBody:
      $ref: "./schemas.yml#/PatchMemberRequestBody"
    PostProjectRequestBody:
      $ref: "./schemas.yml#/PostProjectRequestBody"
    PostPerchMountRequestBody:
      $ref: "./schemas.yml#/PostPerchMountRequestBody"
    PatchPerchMountRequestBody:
      $ref: "./schemas.yml#/PatchPerchMountRequestBody"
    PutPerchMountClaimerRequestBody:
      $ref: "./schemas.yml#/PutPerchMountClaimerRequestBody"
    PostSectionRequestBody:
      $ref: "./schemas.yml#/PostSectionRequestBody"
    PatchSectionRequestBody:
      $ref: "./schemas.yml#/PatchSectionRequestBody"
    PostUnreviewedMediaByDetectedRequestBody:
      $ref: "./schemas.yml#/PostUnreviewedMediaByDetectedRequestBody"
    PostUnreviewedMediaByEmptyCheckedRequestBody:
      $ref: "./schemas.yml#/PostUnreviewedMediaByEmptyCheckedRequestBody"
    PostReviewMediaRequestBody:
      $ref: "./schemas.yml#/PostReviewMediaRequestBody"
    PostAccidentalMediaRequestBody:
      $ref: "./schemas.yml#/PostAccidentalMediaRequestBody"
    PostNewDataRequestBody:
      $ref: "./schemas.yml#/PostNewDataRequestBody"
    PostIdentifiedPreyIndividualsRequestBody:
      $ref: "./schemas.yml#/PostIdentifiedPreyIndividualsRequestBody"

  parameters:
    MemberPositionIDsQuery:
      $ref: "./parameters.yml#/MemberPositionIDsQuery"
    ClaimByIDsQuery:
      $ref: "./parameters.yml#/ClaimByIDsQuery"
    ProjectIDsQuery:
      $ref: "./parameters.yml#/ProjectIDsQuery"
    HabitatIDsQuery:
      $ref: "./parameters.yml#/HabitatIDsQuery"
    PerchMountIDsQuery:
      $ref: "./parameters.yml#/PerchMountIDsQuery"
    SectionSwappedDateFromQuery:
      $ref: "./parameters.yml#/SectionSwappedDateFromQuery"
    SectionSwappedDateToQuery:
      $ref: "./parameters.yml#/SectionSwappedDateToQuery"
    SectionSwapperIDsQuery:
      $ref: "./parameters.yml#/SectionSwapperIDsQuery"
    PerchMountTerminatedQuery:
      $ref: "./parameters.yml#/PerchMountTerminatedQuery"
    MediaStatusQuery:
      $ref: "./parameters.yml#/MediaStatusQuery"
    IndividualsPreyIdentifiedStatusQuery:
      $ref: "./parameters.yml#/IndividualsPreyIdentifiedStatusQuery"
    IndividualsHasPreyQuery:
      $ref: "./parameters.yml#/IndividualsHasPreyQuery"
    IndividualsPreyInaturalistTaxaIDSearchQuery:
      $ref: "./parameters.yml#/IndividualsPreyInaturalistTaxaIDSearchQuery"
    IndividualsIsTaggedQuery:
      $ref: "./parameters.yml#/IndividualsIsTaggedQuery"
    IndividualsRingNumberSearchQuery:
      $ref: "./parameters.yml#/IndividualsRingNumberSearchQuery"
    TaxonOrderByAIQuery:
      $ref: "./parameters.yml#/TaxonOrderByAIQuery"
    TaxonOrderByHumanQuery:
      $ref: "./parameters.yml#/TaxonOrderByHumanQuery"
    SectionIDsQuery:
      $ref: "./parameters.yml#/SectionIDsQuery"
    OffsetQuery:
      $ref: "./parameters.yml#/OffsetQuery"
    LimitQuery:
      $ref: "./parameters.yml#/LimitQuery"
    SpeciesConservationStatusQuery:
      $ref: "./parameters.yml#/SpeciesConservationStatusQuery"
    SpeciesEndemismQuery:
      $ref: "./parameters.yml#/SpeciesEndemismQuery"
    SpeciesNameSearchQuery:
      $ref: "./parameters.yml#/SpeciesNameSearchQuery"
    SpeciesChineseNameSearchQuery:
      $ref: "./parameters.yml#/SpeciesChineseNameSearchQuery"
    SpeciesEnglishNameSearchQuery:
      $ref: "./parameters.yml#/SpeciesEnglishNameSearchQuery"
    SpeciesScientificNameSearchQuery:
      $ref: "./parameters.yml#/SpeciesScientificNameSearchQuery"
    SpeciesOrderQuery:
      $ref: "./parameters.yml#/SpeciesOrderQuery"
    SpeciesFamilyQuery:
      $ref: "./parameters.yml#/SpeciesFamilyQuery"
    PerchMountIDPathParam:
      $ref: "./parameters.yml#/PerchMountIDPathParam"
    SectionIDPathParam:
      $ref: "./parameters.yml#/SectionIDPathParam"
    MemberIDPathParam:
      name: MemberID
      in: path
      required: true
      schema:
        type: string
        format: uuid
    MediumIDPathParam:
      $ref: "./parameters.yml#/MediumIDPathParam"
    IndividualIDPathParam:
      $ref: "./parameters.yml#/IndividualIDPathParam"
    SpeciesTaxonOrderPathParam:
      $ref: "./parameters.yml#/SpeciesTaxonOrderPathParam"

  responses:
    MemberResponse:
      $ref: "./responses.yml#/MemberResponse"
    MembersResponse:
      $ref: "./responses.yml#/MembersResponse"
    PerchMountsResponse:
      $ref: "./responses.yml#/PerchMountsResponse"
    PerchMountResponse:
      $ref: "./responses.yml#/PerchMountResponse"
    ProjectsResponse:
      $ref: "./responses.yml#/ProjectsResponse"
    ProjectResponse:
      $ref: "./responses.yml#/ProjectResponse"
    SectionsResponse:
      $ref: "./responses.yml#/SectionsResponse"
    SectionResponse:
      $ref: "./responses.yml#/SectionResponse"
    MediaResponse:
      $ref: "./responses.yml#/MediaResponse"
    MediumResponse:
      $ref: "./responses.yml#/MediumResponse"
    MeidumPostResponse:
      $ref: "./responses.yml#/MeidumPostResponse"
    IndividualResponse:
      $ref: "./responses.yml#/IndividualResponse"
    PostNewDataResponse:
      $ref: "./responses.yml#/PostNewDataResponse"
    BehaviorResponse:
      $ref: "./responses.yml#/BehaviorResponse"
    BehaviorsResponse:
      $ref: "./responses.yml#/BehaviorsResponse"
    CameraResponse:
      $ref: "./responses.yml#/CameraResponse"
    CamerasResponse:
      $ref: "./responses.yml#/CamerasResponse"
    EventResponse:
      $ref: "./responses.yml#/EventResponse"
    EventsResponse:
      $ref: "./responses.yml#/EventsResponse"
    MountTypeResponse:
      $ref: "./responses.yml#/MountTypeResponse"
    MountTypesResponse:
      $ref: "./responses.yml#/MountTypesResponse"
    PositionsResponse:
      $ref: "./responses.yml#/PositionsResponse"
    HabitatsResponse:
      $ref: "./responses.yml#/HabitatsResponse"
    MountLayersResponse:
      $ref: "./responses.yml#/MountLayersResponse"
    SpeciesResponse:
      $ref: "./responses.yml#/SpeciesResponse"
    SpeciesListResponse:
      $ref: "./responses.yml#/SpeciesListResponse"
