MemberPositionIDsQuery:
  name: position_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

ClaimByIDsQuery:
  name: claim_by_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid
ProjectIDsQuery:
  name: project_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid
HabitatIDsQuery:
  name: habitat_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

PerchMountIDsQuery:
  name: perch_mount_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

SectionSwappedDateFromQuery:
  name: swapped_date_from
  in: query
  schema:
    type: string
    format: date-time

SectionSwappedDateToQuery:
  name: swapped_date_to
  in: query
  schema:
    type: string
    format: date-time

SectionSwapperIDsQuery:
  name: swapper_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

PerchMountTerminatedQuery:
  name: terminated
  in: query
  required: false
  schema:
    type: boolean

MediaStatusQuery:
  name: media_status
  in: query
  required: true
  schema:
    type: string
    enum: [undetected, detected, unchecked, reviewed, accidental]

IndividualsPreyIdentifiedStatusQuery:
  name: prey_identified_status
  in: query
  required: false
  schema:
    type: string
    enum: [unchecked, unidentified, identified]

IndividualsHasPreyQuery:
  name: has_prey
  in: query
  required: false
  schema:
    type: boolean

IndividualsPreyInaturalistTaxaIDSearchQuery:
  name: inaturalist_taxa_id
  in: query
  required: false
  schema:
    type: integer

IndividualsIsTaggedQuery:
  name: is_tagged
  in: query
  required: false
  schema:
    type: boolean

IndividualsRingNumberSearchQuery:
  name: ring_number
  in: query
  required: false
  schema:
    type: string

TaxonOrderByAIQuery:
  name: taxon_order_by_ai
  in: query
  required: false
  schema:
    style: form
    explode: false
    schema:
      type: array
      items:
        type: integer

TaxonOrderByHumanQuery:
  name: taxon_order_by_human
  in: query
  required: false
  schema:
    style: form
    explode: false
    schema:
      type: array
      items:
        type: integer

SectionIDsQuery:
  name: section_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

OffsetQuery:
  name: offset
  in: query
  required: false
  schema:
    type: integer

LimitQuery:
  name: Limit
  in: query
  required: false
  schema:
    type: integer

SpeciesConservationStatusQuery:
  name: conservation_status
  in: query
  required: false
  schema:
    type: string
    enum: [i, ii, iii]

SpeciesEndemismQuery:
  name: endemism
  in: query
  required: false
  schema:
    type: string
    enum: [not_endemic, endemic_species, iendemic_subspecies]

SpeciesNameSearchQuery:
  name: name_search
  in: query
  required: false
  schema:
    type: string

SpeciesChineseNameSearchQuery:
  name: chinese_name_search
  in: query
  required: false
  schema:
    type: string

SpeciesEnglishNameSearchQuery:
  name: english_name_search
  in: query
  required: false
  schema:
    type: string

SpeciesScientificNameSearchQuery:
  name: scientific_name_search
  in: query
  required: false
  schema:
    type: string

SpeciesOrderQuery:
  name: swapper_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

SpeciesFamilyQuery:
  name: swapper_ids
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
      format: uuid

PerchMountIDPathParam:
  name: PerchMountID
  in: path
  required: true
  schema:
    type: string
    format: uuid

SectionIDPathParam:
  name: SectionID
  in: path
  required: true
  schema:
    type: string
    format: uuid

MemberIDPathParam:
  name: MemberID
  in: path
  required: true
  schema:
    type: string
    format: uuid

MediumIDPathParam:
  name: MediumID
  in: path
  required: true
  schema:
    type: string
    format: uuid

IndividualIDPathParam:
  name: IndividualID
  in: path
  required: true
  schema:
    type: string
    format: uuid

SpeciesTaxonOrderPathParam:
  name: TaxonOrder
  in: path
  required: true
  schema:
    type: string
    format: uuid
