openapi: "3.0.3"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://api.server.test/v1

paths:
  /members:
    get:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberPositionIDsQuery"
      responses:
        "200":
          description: OK
    post:
      tags:
        - Member
      responses:
        "200":
          description: OK

  /members/{MemberID}:
    get:
      tags:
        - Member
      parameters:
        - $ref: "#/components/parameters/MemberIDPathParam"
      responses:
        "200":
          description: OK

  /projects:
    get:
      tags:
        - Project
      responses:
        "200":
          description: OK

  /perch_mounts:
    get:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/ProjectIDsQuery"
        - $ref: "#/components/parameters/ClaimByIDsQuery"
        - $ref: "#/components/parameters/HabitatIDsQuery"
        - $ref: "#/components/parameters/PerchMountTerminatedQuery"
      responses:
        "200":
          description: OK
    post:
      tags:
        - Perch Mount
      responses:
        "200":
          description: OK

  /perch_mounts/{PerchMountID}:
    get:
      tags:
        - Perch Mount
      parameters:
        - $ref: "#/components/parameters/PerchMountIDPathParam"
      responses:
        "200":
          description: OK

  /sections:
    get:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/PerchMountIDsQuery"
        - $ref: "#/components/parameters/SectionSwappedDateFromQuery"
        - $ref: "#/components/parameters/SectionSwappedDateToQuery"
        - $ref: "#/components/parameters/SectionSwapperIDsQuery"
      responses:
        "200":
          description: OK
    post:
      tags:
        - Section
      responses:
        "200":
          description: OK

  /sections/{SectionID}:
    get:
      tags:
        - Section
      parameters:
        - $ref: "#/components/parameters/SectionIDPathParam"
      responses:
        "200":
          description: OK

  /media:
    get:
      tags:
        - Media
      parameters:
        - $ref: "#/components/parameters/MediaStatusQuery"
        - $ref: "#/components/parameters/SectionIDsQuery"
        - $ref: "#/components/parameters/OffsetQuery"
        - $ref: "#/components/parameters/LimitQuery"

      responses:
        "200":
          description: OK

  /media/{MediumID}:
    get:
      tags:
        - Media
      parameters:
        - $ref: "#/components/parameters/MediumIDPathParam"
      responses:
        "200":
          description: OK

  /unchecked_media:
    post:
      tags:
        - Media
      responses:
        "200":
          description: OK

  /detected_media:
    post:
      tags:
        - Media
      responses:
        "200":
          description: OK

  /reviewed_media:
    post:
      tags:
        - Media
      responses:
        "200":
          description: OKxx

  /accidental_media:
    post:
      tags:
        - Media
      responses:
        "200":
          description: OK

  /individuals:
    get:
      tags:
        - Individuals
      parameters:
        - $ref: "#/components/parameters/IndividualsPreyStatusQuery"
      responses:
        "200":
          description: OK

  /individuals/identified_preys:
    post:
      tags:
        - Individuals
      responses:
        "200":
          description: OK

  /behaviors:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK
    post:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /positions:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /habitats:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /cameras:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK
    post:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /events:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK
    post:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /mount_types:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK
    post:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /mount_layers:
    get:
      tags:
        - Options
      responses:
        "200":
          description: OK
    post:
      tags:
        - Options
      responses:
        "200":
          description: OK

  /species:
    get:
      tags:
        - species
      parameters:
        - $ref: "#/components/parameters/SpeciesChineseNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesEndemismQuery"
        - $ref: "#/components/parameters/SpeciesEnglishNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesFamilyQuery"
        - $ref: "#/components/parameters/SpeciesNameSearchQuery"
        - $ref: "#/components/parameters/SpeciesOrderQuery"
        - $ref: "#/components/parameters/SpeciesScientificNameSearchQuery"
      responses:
        "200":
          description: OK

  /species/{TaxonOrder}:
    get:
      tags:
        - species
      parameters:
        - $ref: "#/components/parameters/SpeciesTaxonOrderPathParam"
      responses:
        "200":
          description: OK

components:
  parameters:
    MemberPositionIDsQuery:
      name: position_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    ClaimByIDsQuery:
      name: claim_by_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid
    ProjectIDsQuery:
      name: project_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid
    HabitatIDsQuery:
      name: habitat_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    PerchMountIDsQuery:
      name: perch_mount_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    SectionSwappedDateFromQuery:
      name: swapped_date_from
      in: query
      schema:
        type: string
        format: date-time

    SectionSwappedDateToQuery:
      name: swapped_date_to
      in: query
      schema:
        type: string
        format: date-time

    SectionSwapperIDsQuery:
      name: swapper_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    PerchMountTerminatedQuery:
      name: terminated
      in: query
      required: false
      schema:
        type: boolean

    MediaStatusQuery:
      name: media_status
      in: query
      required: true
      schema:
        type: string
        enum: [undetected, detected, unchecked, reviewed, accidental]

    IndividualsPreyStatusQuery:
      name: prey_status
      in: query
      required: false
      schema:
        type: string
        enum: [unchecked, has_prey, no_prey, identified]

    SectionIDsQuery:
      name: section_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    OffsetQuery:
      name: offset
      in: query
      required: false
      schema:
        type: integer

    LimitQuery:
      name: offset
      in: query
      required: false
      schema:
        type: integer

    SpeciesConservationStatusQuery:
      name: conservation_status
      in: query
      required: false
      schema:
        type: string
        enum: [i, ii, iii]

    SpeciesEndemismQuery:
      name: endemism
      in: query
      required: false
      schema:
        type: string
        enum: [not_endemic, endemic_species, iendemic_subspecies]

    SpeciesNameSearchQuery:
      name: name_search
      in: query
      required: false
      schema:
        type: string

    SpeciesChineseNameSearchQuery:
      name: chinese_name_search
      in: query
      required: false
      schema:
        type: string

    SpeciesEnglishNameSearchQuery:
      name: english_name_search
      in: query
      required: false
      schema:
        type: string

    SpeciesScientificNameSearchQuery:
      name: scientific_name_search
      in: query
      required: false
      schema:
        type: string

    SpeciesOrderQuery:
      name: swapper_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    SpeciesFamilyQuery:
      name: swapper_ids
      in: query
      required: false
      style: form
      explode: false
      schema:
        type: array
        items:
          type: string
          format: uuid

    PerchMountIDPathParam:
      name: PerchMountID
      in: path
      required: true
      schema:
        type: string
        format: uuid

    SectionIDPathParam:
      name: SectionID
      in: path
      required: true
      schema:
        type: string
        format: uuid

    MemberIDPathParam:
      name: MemberID
      in: path
      required: true
      schema:
        type: string
        format: uuid

    MediumIDPathParam:
      name: MediumID
      in: path
      required: true
      schema:
        type: string
        format: uuid

    SpeciesTaxonOrderPathParam:
      name: TaxonOrder
      in: path
      required: true
      schema:
        type: string
        format: uuid

  schemas:
    PerchMountHabitats:
      type: string
      enum:
        - natural
        - artificial
        - solar_panel
    PerchMountLayers:
      type: string
      enum:
        - high
        - middle
        - low
    MemberPositions:
      type: string
      enum:
        - professor
        - postdoc
        - doctor
        - master
        - undergrad
        - assistant
        - part_time
    PreyStatus:
      type: string
      enum:
        - unchecked
        - has_prey
        - no_prey
        - identified
    TagStatus:
      type: string
      enum:
        - unchecked
        - ring
        - tagged
        - number_assigned
    ConservationStatus:
      type: string
      enum:
        - I
        - II
        - III

    MediaType:
      type: string
      enum:
        - image
        - video

    Member:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        gmail:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        position:
          $ref: "#/components/schemas/MemberPositions"

    Section:
      type: object
      properties:
        id:
          type: string
          format: uuid
        perch_mount_id:
          type: string
          format: uuid
        mount_type_id:
          type: string
          format: uuid
        swapped_date:
          type: string
          format: date
        camera_id:
          type: string
          format: uuid
        swapper_ids:
          type: array
          items:
            type: string
            format: uuid
        ground_camera:
          type: boolean
        valid:
          type: boolean
        note:
          type: string

    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    PerchMount:
      type: object
      properties:
        id:
          type: string
          format: uuid
        perch_mount_name:
          type: string
        latitude:
          type: number
          format: float
          minimum: -90
          maximum: 90
          example: 37.7749
        longitude:
          type: number
          format: float
          minimum: -180
          maximum: 180
          example: -122.4194
        mount_type:
          type: string
        project_id:
          type: string
          format: uuid
        project_name:
          type: string
        claim_by:
          type: string
          format: uuid
        is_priority:
          type: boolean
        terminated:
          type: boolean
        layer:
          $ref: "#/components/schemas/PerchMountLayers"
        habitat:
          $ref: "#/components/schemas/PerchMountHabitats"
        note:
          type: string

    UndetectedMedium:
      type: object
      properties:
        id:
          type: string
          format: uuid
        section_id:
          type: string
          format: uuid
        medium_time:
          type: string
          format: date-time
        create_time:
          type: string
          format: date-time
        type:
          $ref: "#/components/schemas/MediaType"
        nas_path:
          type: string

    EmtpyMedium:
      properties:
        id:
          type: string
          format: uuid
        section_id:
          type: string
          format: uuid
        medium_time:
          type: string
          format: date-time
        create_time:
          type: string
          format: date-time
        detected_time:
          type: string
          format: date-time
        type:
          $ref: "#/components/schemas/MediaType"
        nas_path:
          type: string

    DetectedMedium:
      properties:
        id:
          type: string
          format: uuid
        section_id:
          type: string
          format: uuid
        medium_time:
          type: string
          format: date-time
        create_time:
          type: string
          format: date-time
        detected_time:
          type: string
          format: date-time
        empty_checked_time:
          type: string
          format: date-time
        empty_checker_id:
          type: string
          format: uuid
        type:
          $ref: "#/components/schemas/MediaType"
        nas_path:
          type: string
        individual_ids:
          type: array
          items:
            type: string
            format: uuid

    ReviewMedium:
      properties:
        id:
          type: string
          format: uuid
        section_id:
          type: string
          format: uuid
        medium_time:
          type: string
          format: date-time
        create_time:
          type: string
          format: date-time
        detected_time:
          type: string
          format: date-time
        reviewed_time:
          type: string
          format: date-time
        reviewer_id:
          type: string
          format: uuid
        empty_checked_time:
          type: string
          format: date-time
        empty_checker_id:
          type: string
          format: uuid
        fetured_by_id:
          type: string
          format: uuid
        event_id:
          type: string
          format: uuid
        behaviour_id:
          type: string
          format: uuid
        type:
          $ref: "#/components/schemas/MediaType"
        nas_path:
          type: string
        individual_ids_by_ai:
          type: array
          items:
            type: string
            format: uuid
        individual_ids_by_human:
          type: array
          items:
            type: string
            format: uuid

    DetectedIndividuals:
      type: object
      properties:
        id:
          type: string
          format: uuid
        medium_id:
          type: string
          format: uuid
        taxon_order_by_ai:
          type: integer
        xmin:
          type: number
          format: float
          maximum: 1
          minimum: 0
        ymin:
          type: number
          format: float
          maximum: 1
          minimum: 0
        xmax:
          type: number
          format: float
          maximum: 1
          minimum: 0
        ymax:
          type: number
          format: float
          maximum: 1
          minimum: 0

    # Should rethink the prey status design
    ReviewIndividuals:
      type: object
      properties:
        id:
          type: string
          format: uuid
        medium_id:
          type: string
          format: uuid
        taxon_order_by_human:
          type: integer
        xmin:
          type: number
          format: float
          maximum: 1
          minimum: 0
        ymin:
          type: number
          format: float
          maximum: 1
          minimum: 0
        xmax:
          type: number
          format: float
          maximum: 1
          minimum: 0
        ymax:
          type: number
          format: float
          maximum: 1
          minimum: 0

    Camera:
      type: object
      properties:
        id:
          type: string
          format: uuid
        model_name:
          type: string

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        chinese_name:
          type: string
        english_name:
          type: string

    Behavior:
      type: object
      properties:
        id:
          type: string
          format: uuid
        chinese_name:
          type: string
        english_name:
          type: string

    MountType:
      type: object
      properties:
        id:
          type: string
          format: uuid
        chinese_name:
          type: string

    Species:
      type: object
      properties:
        taxon_order:
          type: integer
        scientific_name:
          type: string
        english_common_name:
          type: string
        chinese_common_name:
          type: string
        order:
          type: string
        family_name:
          type: string
        family_latin_name:
          type: string
        taiwan_status:
          type: string
        matzu_status:
          type: string
        kinmen_status:
          type: string
        pratas_status:
          type: string
        endemism:
          type: string
        conservation_status:
          $ref: "#/components/schemas/ConservationStatus"
