"""longer camera model name

Revision ID: 79853b2e335b
Revises: 243736b62080
Create Date: 2024-04-10 23:43:42.705225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79853b2e335b'
down_revision = '243736b62080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
