"""migrate for download

Revision ID: 883770a5b1e5
Revises: dab29e7eb617
Create Date: 2024-03-30 14:09:55.088182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '883770a5b1e5'
down_revision = 'dab29e7eb617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.drop_index('file_name')

    op.drop_table('export_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_history',
    sa.Column('export_history_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('exportor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('expire_time', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['exportor'], ['members.member_id'], name='export_history_ibfk_1'),
    sa.PrimaryKeyConstraint('export_history_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.create_index('file_name', ['file_name'], unique=True)

    # ### end Alembic commands ###
