"""init tables

Revision ID: 8f214f0af359
Revises: 
Create Date: 2025-02-15 11:54:42.243985

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations_custom import utils, data_init

# revision identifiers, used by Alembic.
revision = "8f214f0af359"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    utils.create_extensions()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "behaviors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("model_name"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("gmail", postgresql.CITEXT(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column(
            "position",
            sa.Enum(
                "PROFESSOR",
                "POSTDPC",
                "DOCTOR",
                "MASTER",
                "UNDERGRAD",
                "ASSISTANT",
                "PART_TIME",
                name="positions",
            ),
            nullable=True,
        ),
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column(
            "is_super_admin",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column(
            "blocked", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column(
            "activated", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gmail"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_name"),
    )
    op.create_table(
        "mount_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "species",
        sa.Column("taxon_order", sa.Integer(), nullable=False),
        sa.Column("scientific_name", sa.String(length=100), nullable=False),
        sa.Column("english_common_name", sa.String(length=100), nullable=True),
        sa.Column("chinese_common_name", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=15), nullable=True),
        sa.Column("order", sa.String(length=50), nullable=True),
        sa.Column("family_name", sa.String(length=50), nullable=True),
        sa.Column("family_latin_name", sa.String(length=50), nullable=True),
        sa.Column("taiwan_status", sa.String(length=50), nullable=True),
        sa.Column("matzu_status", sa.String(length=50), nullable=True),
        sa.Column("kinmen_status", sa.String(length=50), nullable=True),
        sa.Column("pratas_status", sa.String(length=50), nullable=True),
        sa.Column("endemism", sa.String(length=50), nullable=True),
        sa.Column(
            "conservation_status",
            sa.Enum("I", "II", "III", name="conservationstatus"),
            nullable=True,
        ),
        sa.Column("codes", postgresql.ARRAY(sa.String(length=10)), nullable=True),
        sa.PrimaryKeyConstraint("taxon_order"),
        sa.UniqueConstraint("chinese_common_name"),
        sa.UniqueConstraint("english_common_name"),
        sa.UniqueConstraint("scientific_name"),
        sa.UniqueConstraint("taxon_order"),
    )
    op.create_table(
        "perch_mounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("perch_mount_name", sa.String(length=15), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column(
            "habitat",
            sa.Enum("NATURAL", "ARTIFICIAL", "SOLAR_PANEL", name="habitats"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("claim_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "mount_layer",
            sa.Enum("LOW", "MIDDLE", "HIGH", name="mountlayers"),
            nullable=False,
        ),
        sa.Column(
            "terminated", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column(
            "is_priority", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_by_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("perch_mount_name"),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("perch_mount_id", sa.UUID(), nullable=False),
        sa.Column("mount_type_id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("swapped_date", sa.Date(), nullable=False),
        sa.Column(
            "valid", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("undetected_count", sa.Integer(), nullable=True),
        sa.Column("unchecked_count", sa.Integer(), nullable=True),
        sa.Column("unreviewed_count", sa.Integer(), nullable=True),
        sa.Column("reviewed_count", sa.Integer(), nullable=True),
        sa.Column("accidental_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mount_type_id"],
            ["mount_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["perch_mount_id"],
            ["perch_mounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("medium_datetime", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "medium_type", sa.Enum("IMAGE", "VIDEO", name="mediatypes"), nullable=False
        ),
        sa.Column("nas_path", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UNDETECTED",
                "UNCHECKED",
                "UNREVIEWED",
                "REVIEWED",
                "ACCIDENTAL",
                name="mediastatus",
            ),
            server_default="UNDETECTED",
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "sections_swappers",
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("swapper_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swapper_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("section_id", "swapper_id"),
    )
    op.create_table(
        "accidental_media_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "individuals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "prey_status",
            sa.Enum(
                "UNDETECTED",
                "UNCHECKED",
                "UNREVIEWED",
                "REVIEWED",
                "ACCIDENTAL",
                name="mediastatus",
            ),
            server_default="UNCHECKED",
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "media_checked_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.Column("empty_checked_at", sa.DateTime(), nullable=True),
        sa.Column("empty_checker_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["empty_checker_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "media_detected_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "reviewed_media_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("fearured_by_id", sa.UUID(), nullable=True),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("behavior_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["behavior_id"],
            ["behaviors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fearured_by_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "unchecked_media_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "undetected_media_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "unreviewed_media_contents",
        sa.Column("medium_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medium_id"],
            ["media.id"],
        ),
        sa.PrimaryKeyConstraint("medium_id"),
    )
    op.create_table(
        "identified_prey_individuals_contents",
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("inaturalist_taxa_id", sa.Integer(), nullable=False),
        sa.Column("identifier_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["identifier_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
        ),
        sa.PrimaryKeyConstraint("individual_id"),
    )
    op.create_table(
        "marked_prey_individuals_contents",
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("has_prey", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
        ),
        sa.PrimaryKeyConstraint("individual_id"),
    )
    op.create_table(
        "reviewed_individuals_contents",
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("taxon_order_by_human", sa.Integer(), nullable=False),
        sa.Column("box_xmin", sa.Float(), nullable=True),
        sa.Column("box_xmax", sa.Float(), nullable=True),
        sa.Column("box_ymin", sa.Float(), nullable=True),
        sa.Column("box_ymax", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["taxon_order_by_human"],
            ["species.taxon_order"],
        ),
        sa.PrimaryKeyConstraint("individual_id"),
    )
    op.create_table(
        "tagged_individuals_contents",
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("is_tagged", sa.Boolean(), nullable=False),
        sa.Column("has_ring", sa.Boolean(), nullable=False),
        sa.Column("ring_number", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
        ),
        sa.PrimaryKeyConstraint("individual_id"),
    )
    op.create_table(
        "unreviewed_individuals_contents",
        sa.Column("individual_id", sa.UUID(), nullable=False),
        sa.Column("taxon_order_by_ai", sa.Integer(), nullable=False),
        sa.Column("box_xmin", sa.Float(), nullable=True),
        sa.Column("box_xmax", sa.Float(), nullable=True),
        sa.Column("box_ymin", sa.Float(), nullable=True),
        sa.Column("box_ymax", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["individual_id"],
            ["individuals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["taxon_order_by_ai"],
            ["species.taxon_order"],
        ),
        sa.PrimaryKeyConstraint("individual_id"),
    )
    # ### end Alembic commands ###

    utils.upgrade_ext()
    data_init.init_species()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unreviewed_individuals_contents")
    op.drop_table("tagged_individuals_contents")
    op.drop_table("reviewed_individuals_contents")
    op.drop_table("marked_prey_individuals_contents")
    op.drop_table("identified_prey_individuals_contents")
    op.drop_table("unreviewed_media_contents")
    op.drop_table("undetected_media_contents")
    op.drop_table("unchecked_media_contents")
    op.drop_table("reviewed_media_contents")
    op.drop_table("media_detected_contents")
    op.drop_table("media_checked_contents")
    op.drop_table("individuals")
    op.drop_table("accidental_media_contents")
    op.drop_table("sections_swappers")
    op.drop_table("media")
    op.drop_table("sections")
    op.drop_table("perch_mounts")
    op.drop_table("species")
    op.drop_table("projects")
    op.drop_table("mount_types")
    op.drop_table("members")
    op.drop_table("events")
    op.drop_table("cameras")
    op.drop_table("behaviors")
    # ### end Alembic commands ###

    utils.downgrade_ext()
