"""Contributions

Revision ID: 93f7b54c2c5d
Revises: c4b37d7cbb1b
Create Date: 2025-05-15 20:30:46.287514

"""

from alembic import op
import sqlalchemy as sa
from migrations_custom import _93f7b54c2c5d_utils

# revision identifiers, used by Alembic.
revision = "93f7b54c2c5d"
down_revision = "c4b37d7cbb1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "contribution_type",
            sa.Enum("REVIEW", "EMPTY_CHECK", "IDENTIFY_PREY", name="contributiontype"),
            nullable=False,
        ),
        sa.Column("counts", sa.Integer(), nullable=False),
        sa.Column("contributor_id", sa.UUID(), nullable=False),
        sa.Column(
            "contribute_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("contributions")

    _93f7b54c2c5d_utils.downgrade_ext()
    # ### end Alembic commands ###
