"""create table: export_history

Revision ID: de0028ff0a62
Revises: dab29e7eb617
Create Date: 2024-03-27 00:46:27.888869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0028ff0a62'
down_revision = 'dab29e7eb617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_history',
    sa.Column('export_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exportor', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['exportor'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('export_history_id'),
    sa.UniqueConstraint('file_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_history')
    # ### end Alembic commands ###
