"""add create_time amd export_time columns

Revision ID: edbe536b2414
Revises: de0028ff0a62
Create Date: 2024-03-27 00:50:59.063246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbe536b2414'
down_revision = 'de0028ff0a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expire_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.drop_column('expire_time')
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
